# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 04:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20170721_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2017, 7, 21, 4, 27, 17, 143101, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
